In [1]:
import pandas as pd

# Load the dataset
url = '/Users/mohandesigan/Documents/coding/AI/DL-andrew-ng-nbs-/Course 1/Week 4/Extra NBS/bank-additional.csv'
data = pd.read_csv(url, sep=';')
data.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,married,basic.9y,no,yes,no,cellular,may,fri,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
1,39,services,single,high.school,no,no,no,telephone,may,fri,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
2,25,services,married,high.school,no,yes,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.962,5228.1,no
3,38,services,married,basic.9y,no,unknown,unknown,telephone,jun,fri,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4,47,admin.,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Encode the target variable ('yes' -> 1, 'no' -> 0)
data['y'] = data['y'].apply(lambda x: 1 if x == 'yes' else 0)

# Encode categorical features
categorical_features = data.select_dtypes(include=['object']).columns
data = pd.get_dummies(data, columns=categorical_features, drop_first=True)

# Split features and target
X = data.drop('y', axis=1).values
Y = data['y'].values.reshape(1, -1)

# Split into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y.T, test_size=0.2, random_state=1)

In [3]:
# Normalize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).T
X_test = scaler.transform(X_test).T

In [5]:
from cleaned_nn import DeepNeuralNetwork
layer_dims = [X_train.shape[0], 20, 9, 5, 1]  # Example architecture


# Initialize and train the model
model = DeepNeuralNetwork(layer_dims, learning_rate=0.0075, num_iterations=3000, print_cost=True)
parameters, costs = model.fit(X_train, Y_train.T)

Cost after iteration 0: 0.6931468497622202
Cost after iteration 100: 0.5995282563843124
Cost after iteration 200: 0.5347776624950391
Cost after iteration 300: 0.4893511857627762
Cost after iteration 400: 0.45691446544478465
Cost after iteration 500: 0.4333294846003499
Cost after iteration 600: 0.4158834557636115
Cost after iteration 700: 0.40277469519365205
Cost after iteration 800: 0.39278600366750677
Cost after iteration 900: 0.3850798218832661
Cost after iteration 1000: 0.37906925591683754
Cost after iteration 1100: 0.3743358928963012
Cost after iteration 1200: 0.37057660392008207
Cost after iteration 1300: 0.36756851426683934
Cost after iteration 1400: 0.3651455338322072
Cost after iteration 1500: 0.3631823648677803
Cost after iteration 1600: 0.3615834279891726
Cost after iteration 1700: 0.36027507544570947
Cost after iteration 1800: 0.3592000388430156
Cost after iteration 1900: 0.35831341660914323
Cost after iteration 2000: 0.35757973808185234
Cost after iteration 2100: 0.35697079122941217
Cost after iteration 2200: 0.35646399792949773
Cost after iteration 2300: 0.35604118674267304
Cost after iteration 2400: 0.3556876577769766
Cost after iteration 2500: 0.35539146364024
Cost after iteration 2600: 0.3551428526261281
Cost after iteration 2700: 0.3549338341428837
Cost after iteration 2800: 0.3547578373132135
Cost after iteration 2900: 0.3546094410739892
Cost after iteration 2999: 0.35448531085307

In [7]:
import numpy as np
# Make predictions
Y_prediction_test = model.predict(X_test)
Y_prediction_train = model.predict(X_train)

# Calculate accuracy
test_accuracy = np.mean(Y_prediction_test == Y_test)
train_accuracy = np.mean(Y_prediction_train == Y_train)

print(f"Train accuracy: {train_accuracy:.2%}")
print(f"Test accuracy: {test_accuracy:.2%}")
from cleaned_nn import DeepNeuralNetwork
#Define the layer dimensions (input layer size should match the number of features)

Train accuracy: 88.65%
Test accuracy: 90.66%

In [8]:
import numpy as np
# Forward propagation on the test set
AL_test, _ = model.L_model_forward(X_test)

# Convert probabilities to binary predictions
predictions = (AL_test > 0.5).astype(int)

# Calculate accuracy
accuracy = np.mean(predictions == Y_test)

print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.9065533980582524

In [12]:
from improved_clnn import DeepNeuralNetwork
layer_dims = [X_train.shape[0], 20, 9, 5, 1]  # Example architecture


# Initialize and train the model
model = DeepNeuralNetwork(layer_dims, learning_rate=0.0075, num_iterations=7000, print_cost=True)
parameters, costs = model.fit(X_train, Y_train.T)

Cost after iteration 0: 1.2167945483877856
Cost after iteration 100: 2.165999031249575
Cost after iteration 200: 6.963447293689082
Cost after iteration 300: 4.490192265977109
Cost after iteration 400: 3.593878954393284
Cost after iteration 500: 2.869403230726622
Cost after iteration 600: 2.830629660376622
Cost after iteration 700: 2.6781734924028195
Cost after iteration 800: 2.7537525356413766
Cost after iteration 900: 2.2437562718235946
Cost after iteration 1000: 1.7527214988734598
Cost after iteration 1100: 2.1830510252584365
Cost after iteration 1200: 1.815762576275686
Cost after iteration 1300: 1.8210401675266383
Cost after iteration 1400: 1.9616226051755181
Cost after iteration 1500: 1.9590706267850315
Cost after iteration 1600: 2.050946900231969
Cost after iteration 1700: 1.950438412551815
Cost after iteration 1800: 3.707495147764078
Cost after iteration 1900: 3.3754025930305542
Cost after iteration 2000: 2.0715613669738304
Cost after iteration 2100: 2.4563048656354773
Cost after iteration 2200: 3.444746741905996
Cost after iteration 2300: 2.33930770104575
Cost after iteration 2400: 2.375950715809861
Cost after iteration 2500: 2.3869131426450725
Cost after iteration 2600: 2.9687985833473443
Cost after iteration 2700: 3.3188762431019305
Cost after iteration 2800: 3.6652646717724098
Cost after iteration 2900: 3.0952390838867063
Cost after iteration 3000: 3.6968745610207505
Cost after iteration 3100: 3.3076102330722206
Cost after iteration 3200: 3.5272013705083984
Cost after iteration 3300: 3.716400800951786
Cost after iteration 3400: 3.494460679309974
Cost after iteration 3500: 3.7103014773092284
Cost after iteration 3600: 3.811789261426697
Cost after iteration 3700: 3.9167912526656155
Cost after iteration 3800: 3.902478301582936
Cost after iteration 3900: 3.9864479381946976
Cost after iteration 4000: 3.9050796847189533
Cost after iteration 4100: 3.8794514700572837
Cost after iteration 4200: 3.941508081745854
Cost after iteration 4300: 3.985208617745657
Cost after iteration 4400: 3.9489211629888654
Cost after iteration 4500: 3.9822107425591646
Cost after iteration 4600: 3.903426798363985
Cost after iteration 4700: 3.9850262412813304
Cost after iteration 4800: 3.9659902158806335
Cost after iteration 4900: 4.018889850475087
Cost after iteration 5000: 4.007429698642065
Cost after iteration 5100: 4.007924030099468
Cost after iteration 5200: 4.040174085987369
Cost after iteration 5300: 4.036301412224566
Cost after iteration 5400: 4.038131784300662
Cost after iteration 5500: 4.008974050141842
Cost after iteration 5600: 4.018554285558037
Cost after iteration 5700: 3.990821411290011
Cost after iteration 5800: 4.016097664986863
Cost after iteration 5900: 4.030588749330116
Cost after iteration 6000: 4.0630203965562695
Cost after iteration 6100: 4.065647809022264
Cost after iteration 6200: 4.057163754170175
Cost after iteration 6300: 4.048540725886897
Cost after iteration 6400: 4.057774578667765
Cost after iteration 6500: 4.072249580446438
Cost after iteration 6600: 4.069547987297993
Cost after iteration 6700: 4.0647655277284445
Cost after iteration 6800: 4.065893789266244
Cost after iteration 6900: 4.070733811262996
Cost after iteration 6999: 4.065091210489423

In [13]:
import numpy as np
# Make predictions
Y_prediction_test = model.predict(X_test)
Y_prediction_train = model.predict(X_train)

# Calculate accuracy
test_accuracy = np.mean(Y_prediction_test == Y_test)
train_accuracy = np.mean(Y_prediction_train == Y_train)

print(f"Train accuracy: {train_accuracy:.2%}")
print(f"Test accuracy: {test_accuracy:.2%}")
from cleaned_nn import DeepNeuralNetwork
#Define the layer dimensions (input layer size should match the number of features)

Train accuracy: 88.58%
Test accuracy: 90.56%